name: Close Pull Request
on:
  pull_request:
    types: [opened, review_requested]
    branches: [test-branch]


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "This pull request has been closed because no reviews were submitted."