name: Close Pull Request
run-name: Close Pull Request running by @${{ github.actor }}

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 1 minute
        run: sleep 60 # Sleep for 1 minute (60 seconds)
      - name: Check Review Status
        id: check_review
        run: echo "::set-output name=has_review::$([[ $(gh pr view ${{ github.event.pull_request.number }} --json review_decision -q . == 'null' ]] && echo 'false' || echo 'true')]"
      - name: Close Pull Request
        if: steps.check_review.outputs.has_review == 'false'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "This pull request has been closed because no review was submitted within 1 minutes."
