name: Close Pull Request
run-name: Close Pull Request by @${{ github.actor }}

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 1 minute
        run: sleep 60 # Sleep for 1 minute (60 seconds)
      - name: Close Pull Request
        if: github.event.pull_request.reviews == null
        run: |
          echo "Closing pull request #${{ github.event.pull_request.number }}"
          TOKEN="${{ secrets.PR_Key }}"
          OWNER="${{ github.event.repository.owner.login }}"
          REPO="${{ github.event.repository.name }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          curl -X PATCH -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}" -d '{"state": "closed"}'