name: Close Pull Request
run-name: Close Pull Request running by @${{ github.actor }}

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Wait for 1 minute
        run: sleep 60 # Sleep for 1 minute (60 seconds)
      - name: Check Review Status
        id: check_review
        run: |
          HAS_REVIEW=$(gh pr view $PR_NUMBER --json review_decision -q .)
          if [[ "$HAS_REVIEW" == "null" ]]; then
            echo "has_review=false" >> $GITHUB_ENV
          else
            echo "has_review=true" >> $GITHUB_ENV
          fi
      - name: Close Pull Request
        if: env.has_review == 'false'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "This pull request has been closed because no review was submitted within 1 minute."
