name: Close PR without reviews

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  close_pr_without_reviews:
    runs-on: ubuntu-latest
    steps:
    - name: Check for reviews
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.PR_Key }}
        script: |
          const reviews = await github.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });

          if (reviews.data.length === 0) {
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: 'closed'
            });
          } else {
            console.log('Pull request has reviews, no action needed.');
          }