name: Close Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  close_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 1 minute
        run: sleep 30 # Sleep for 1 minute (60 seconds)
      name: Check if review exists
      id: check_review
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: reviews } = await github.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number});
          return reviews.total_count;
      - name: Close Pull Request
         if: steps.check_review.outputs > 0
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "This pull request has been closed because no review was submitted within 1 minute."