name: Close Pull Request
on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is from specific branch
        if: ${{ github.event.pull_request.head.ref == 'test-branch' }}
        run: |
          echo "Pull request is from 'test-branch'"
          # Add steps to wait and close the pull request here
          # Wait for 2 minutes
          sleep 120
          # Close Pull Request
          echo "Closing the pull request"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge" \
            -d '{"commit_title":"Pull request closed","merge_method":"close"}'
