name: Close Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 1 minutes
        run: sleep 60 # Sleep for 2 minutes (120 seconds)
      - name: Close Pull Request
        if: github.event.pull_request.review_decision == null
        run: |
          echo "Closing pull request #${{ github.event.pull_request.number }}"
          TOKEN="${{ secrets.Test }}" # Update with your new token secret name
          OWNER="${{ github.event.repository.owner.login }}"
          REPO="${{ github.event.repository.name }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          curl -X PATCH -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}" -d '{"state": "closed"}'
