name: Close Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Close Pull Request
        if: github.event.pull_request.review_decision == null
        run: |
          echo "Closing pull request #${{ github.event.pull_request.number }}"
          gh pr close ${{ github.event.pull_request.number }} --delete-branch
