name: Workflow for e-bakery
run-name: tests running by @${{ github.actor }}
on: 
  push:
    branches: [yann]
  pull_request:
    branches: [master]

jobs: 
  run-node: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: use Node.JS
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
      - name: dependances installations
        run: npm install
      - name: run tests
        run: npm test