name: Workflow for e-bakery
on: 
  push:
    branches: [yann]
  pull_request:
    branches: [master]

jobs: 
  run-node: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.JS
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
      - run: npm ci
      - run: npm test